Repository shadowasphodel2919/Cryptogrammer, pull requests merged in 2023-10, with the labels that each got.

#8 Added material UI and added decryption in caeser cipher
  src/Algorithms.jsx
  src/Algos/Affine.jsx
  src/Algos/Caeser.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added contributing.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#16 Added diagram for playfair
  src/Algos/Playfair.jsx
Labels: hacktoberfest-accepted

#17 Added Polybius Cipher
  package-lock.json
  package.json
  src/Algorithms.jsx
  src/Algos/PolybiusCipher.jsx
  src/App.js
Labels: hacktoberfest
